mein/catalog/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]
urlpatterns += [
    path('mybooks/', views.loanedBooksByUserListView.as_view(),name='myborrowed'),
]
urlpatterns += [
    path('other/', views.other, name='otherpage'),
]
urlpatterns += [
    path('anime/', views.anime, name='animevost'),
]
urlpatterns += [
    path('wix/', views.wix, name='wixer'),
]
urlpatterns += [
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]

urlpatterns += [
    path('author/create/',views.AuthorCreate.as_view(),name='author_create'),
    path('author/<int:pk>/update/',views.AuthorUpdate.as_view(),name='author_update'),
    path('author/<int:pk>/delete/',views.AuthorDelete.as_view(),name='author_delete')
    ]

mein/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    ]
urlpatterns += [
    path('catalog/', include('catalog.urls')),
    ]
urlpatterns += [
    path('',RedirectView.as_view(url='/catalog/', permanent=True)),
    ]
urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    ]

mein/catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date
import uuid
class Person(models.Model):
    name = models.CharField(max_length=130)
    email = models.EmailField(blank=True)
    job_title = models.CharField(max_length=30, blank=True)
    bio = models.TextField(blank=True)

class Genre(models.Model):
    """
    Model respresebt
    """
    name = models.CharField(max_length=200, help_text='Enter a book genre(e.g Scie)')
    def __str__(self):
        return self.name

class Book(models.Model):
        title = models.CharField(max_length=200)
        author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
        summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
        isbn = models.CharField('ISBN',max_length=13, help_text="Select a genre for this book")
        genre = models.ManyToManyField(Genre, help_text="select")
        language=models.ForeignKey('language', on_delete = models.SET_NULL, null = True)

        def  __str__(self):
            return self.title
        def get_absolute_urs(self):
            return reverse('book-detail',  args=[str(self.id)])
        def display_genre(self):
            return ', '.join([ genre.name for genre in self.genre.all()[:3] ])
        display_genre.short_description = 'Genre'
class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    
    

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved')
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank = True, default='m', help_text='Book availability')

    class Meta:
        ordering = ['due_back']
    def __str__(self):
        return '%s (%s)' % (self.id, self.book.title)
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False
class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])
    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)
    
class Language(models.Model):
    name = models.CharField(max_length = 100, help_text="lol")
    def __str__(self):
        return self.name

mein/catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm
from .models import BookInstance

class RenewBookForm(forms.Form):
	def clean_renewal_date(self):
		date = self.cleaned_date['due_back']
		if date < datetime.date.today():
			raise ValidationError(_('Invalid date - renewal in past'))
		if date > datetime.date.today() + datetime.timedelta(weels=4):
			raise ValodationError(_('Invalid date - renewal more than 9 week ahead'))
		return date
	class Meta:
                 model = BookInstance
                 fields = ['due_back']
                 labels = {'due_back':_('Renewal date'),}
                 help_text = {'due_back':_('Enter a date between now and 4 week (default 3).'),}

mein/catalog/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.views.generic import CreateView
from .models import Book, Author, BookInstance, Genre, Person
def other(request):
	return render(request, 'others.html')
def anime(request):
	return render(request, 'anime.html')
def wix(request):
    return render(request, 'wix.html')
def index(request):
    num_books=Book.objects.all().count()
    num_instances=BookInstance.objects.all().count()
    num_instances_available=BookInstance.objects.filter(status='a').count()
    num_authors=Author.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    context={'num_books':num_books,
                'num_instances':num_instances,
                'num_instances_available':num_instances_available,
                'num_authors':num_authors,
                'num_visits': num_visits,
                }
        
    return render(request, 'index.html', context=context)
class loanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10
    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from catalog.models import Author

from catalog.forms import RenewBookForm
from django.contrib.auth.decorators import permission_required

@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    book_inst=get_object_or_404(BookInstance, pk=pk)
    if request.method == "POST":
        form = RenewBookForm(request.POST)
        if form.is_valid():
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()
            return HttpResponseRedirect(reverse('all_borrowed'))
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date,})
    return render(request, 'catalog/book_renew_librarian.html', {'form':form, 'book_inst':book_inst})

class AuthorCreate(CreateView):
        model = Author
        fields = '__all__'
        initial = {'date_of_death': '05/01/2018'}
class AuthorUpdate(UpdateView):
        model = Author
        fields =  ['first_name','last_name','date_of_birth','date_of_death']
class AuthorDelete(DeleteView):
        model = Author
        success_url = reverse_lazy('authors')
def wix1(request):
    return render(request, 'wix1.html')

mein/catalog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Django People</title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <h1 class="mt-2">Django People</h1>
          <hr class="mt-0 mb-4">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

mein/catalog/templates/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Maya bee</title>

  <!-- Bootstrap Core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href={%static "vendor/fontawesome-free/css/all.min.css"%} rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
  <link href={%static "vendor/simple-line-icons/css/simple-line-icons.css"%} rel="stylesheet">

  <!-- Custom CSS -->
  <link href={%static "css/stylish-portfolio.min.css"%} rel="stylesheet">

</head>

<body id="page-top">
  

  <!-- Navigation -->
  <a class="menu-toggle rounded" href="#">
    <i class="fas fa-bars"></i>
  </a>
  <nav id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand">
        <a class="js-scroll-trigger" href="#page-top">Maya the bee</a>
      </li>
      <li class="sidebar-nav-item">
        <a class="js-scroll-trigger" href="#page-top">Home</a>
      </li>
      <li class="sidebar-nav-item">
        <a class="js-scroll-trigger" href="#about">Advertising</a>
      </li>
     
      <li class="sidebar-nav-item">
        <a class="js-scroll-trigger" href="#portfolio">Plot</a>
      </li>
      <li class="sidebar-nav-item">
        <a class="js-scroll-trigger" href="#contact">Contact</a>
    </ul>
  </nav>

  <!-- Header -->
  <header class="masthead d-flex">
    <div class="container text-center my-auto">
      <h1 class="mb-1",action = 'center'>maya bee</h1>
      <h2 class="mb-5",action  = 'center'>
        <em>Who is maya bee?</em>
      </h2>
    </div>
	<h2>Adventures of the Maya Bee
	    a children's book by the German writer Waldemar Bonzels
		, published in 1912, filmed in 1975 as an animated series 
		by the Japanese company Nippon Animation .
		In 1982, the second part of the series - "The New Adventures of the Maya Bee" was released.
		In 2012, a 3D animated series with the same name was released.
		September 4, 2014 the world premiere of a full-length 3D animated film 
		(production Germany, Australia) in South Korea. In Russia - October 30, 2014.
	</h2>
	<a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">NEXT ADVERTISING</a>
    <div class="overlay"></div>
	<h1>interesting fact</h1>
	<h2>in 2018 Oleg Vinnik made a song about the Maya bee</h2>
  </header>

  <!-- About -->
  <section class="content-section bg-light" id="about">
    <div class="container text-center">
      <div class="row">
        <div class="col-lg-10 mx-auto">
          <h2 action = 'center'>typical Mayan bee parody</h2>
          <p class="lead mb-5">don't watch
            <iframe width="633" height="506" src="https://www.youtube.com/embed/UCScWmyD3Mg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>Unsplash</iframe>!</p>
          <a class="btn btn-dark btn-xl js-scroll-trigger" href="#services">What We Offer</a>
        </div>
      </div>
    </div>
  </section>

  

  <!-- Callout -->
  <section class="callout">
    <div class="container text-center">
      <h2 class="mx-auto mb-5",action = 'center'>did you watch maya or read? NO then follow the link below</h2>
      <a class="btn btn-primary btn-xl" href="https://royallib.com/book/bonzels_valdemar/pchela_mayya_i_ee_priklyucheniya.html">DowNloAd Maya On Your Pc!</a>
    </div>
  </section>

  <!-- Portfolio -->
  <section class="content-section" id="portfolio">
    <h1 class="text-secondary mb-0",action = 'center'>Plot</h1>
    <h2>Bonzels' original book was rather short and contained less than 200 pages.
	The plot focuses on the relationship of Maya and her society,
	while adventures play a secondary role in the acquisition of life experience by young Maya.
	In the television series, the relative role of adventure has been increased.
	A young honey bee named Maya was born during the time of internal unrest
	- the hive is divided into two new colonies. Maya is raised by her teacher
	, Miss Cassandra. Despite her warnings, Maya is filled with the desire to explore the vast world outside the hive,
	full of magic, fun and miracles, and for the sake of this she commits an unforgivable crime for bees - escape.</h2>    
  </section>

  <!-- Call to Action -->
  <section class="content-section bg-primary text-white">
    <div class="container text-center">
      <h2 class="mb-4",action = 'center'>The buttons below are impossible to resist...</h2>
      <a href="#" class="btn btn-xl btn-light mr-4">Click Me!</a>
      <a href="#" class="btn btn-xl btn-dark">Look at Me!</a>
    </div>
  </section>

  <!-- Map -->
  <section id="contact" class="map">
    <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;aq=0&amp;oq=twitter&amp;sll=28.659344,-81.187888&amp;sspn=0.128789,0.264187&amp;ie=UTF8&amp;hq=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;t=m&amp;z=15&amp;iwloc=A&amp;output=embed"></iframe>
    <br />
    <small>
      <a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;aq=0&amp;oq=twitter&amp;sll=28.659344,-81.187888&amp;sspn=0.128789,0.264187&amp;ie=UTF8&amp;hq=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;t=m&amp;z=15&amp;iwloc=A"></a>
    </small>
  </section>

  <!-- Footer -->
  <footer class="footer text-center">
    <div class="container">
      <ul class="list-inline mb-5">
        <li class="list-inline-item">
          <a class="social-link rounded-circle text-white mr-3" href="#">
            <i class="icon-social-facebook"></i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="social-link rounded-circle text-white mr-3" href="#">
            <i class="icon-social-twitter"></i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="social-link rounded-circle text-white" href="#">
            <i class="icon-social-github"></i>
          </a>
        </li>
      </ul>
      <p class="text-muted small mb-0">Copyright &copy; Your Website 2019</p>
    </div>
  </footer>

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded js-scroll-trigger" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Bootstrap core JavaScript -->
  <script src={%static "vendor/jquery/jquery.min.js"%}></script>
  <script src={%static "vendor/bootstrap/js/bootstrap.bundle.min.js"%}></script>

  <!-- Plugin JavaScript -->
  <script src={%static "vendor/jquery-easing/jquery.easing.min.js"%}></script>

  <!-- Custom scripts for this template -->
  <script src={%static "js/stylish-portfolio.min.js"%}></script>

</body>

</html>

mein/catalog/templates/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}
{% block content %}
<h1>Borrowed books</h1>
{% if bookinstance_list %}
<ul>
	{% for bookinst in bookinstance_list %}
	<li class="{% if boolinst.is_overdue %}text-danger{% endif %}">
		<a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
	</li>
	{% endfor %}
</ul>
{% else %}
<p>There are no books borrowed</p>
{% endif %}
{% endblock %}

mein/catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author </h1>

<p>Are you sure you want to delete the author:{{ author }}?</p>
<form action="" method="POST">
    {% csrf_token %}
	<input type="submit" value="Yes, delete">
</form>

{% endblock %}

mein/catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}
{% block content %}

<form action="" merhod="post">
    {% csrf_token %}
	<table>
	{{ form.as_table }}
	</table>
	<input type="submit" value="Submit" />
	
</form>
{% endblock %}

mein/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}
<h1>Renew: {{ book_instance.book.title }}</h1>
<p>Borrower: {{ book_instance.borrower }}</p>
<p {% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>
<form action="" method="post">
	{% csrf_token %}
	<table>
	{{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

mein/catalog/templates/index.html
{% extends 'base_generic.html' %}
{% block content %}
<h1>Local Library Home</h1>
  <p>Welcome to <em>LocalLibrary</em>, a very basic Django website</p>
<h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  




{% endblock %}